spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pratyushvatsalshukla/ConfigServerRepo
          default-label: main
          clone-on-start: true
  application:
    name: Config-Server


  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true

server:
  port: 8082